name: Send Email Notification

on:
  workflow_run:
    workflows: ["Name_of_your_workflow"]
    types:
      - completed

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Email
        run: |
          curl -s --user 'api:key-yourSendGridAPIKey' \
          --url 'https://api.sendgrid.com/v3/mail/send' \
          --header 'Content-Type: application/json' \
          --data '{"personalizations": [{"to": [{"email": "Wajsar.Josef@hotmail.com"}]}],"from": {"email": "sender@example.com"},"subject": "Subject of the email","content": [{"type": "text/plain", "value": "Body of the email"}]}'
